language: scala
sudo: false
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - jdk: openjdk7
    - jdk: oraclejdk7
    - jdk: oraclejdk8
script:
  - make all
after_success:
    - bash <(curl -s https://codecov.io/bash)
